name: Clean older images - dry
on:
#   schedule:
#     - cron: '00 5 * * 2'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cleanup-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
            package: aurora-dx
            delete-orphaned-images: true
            keep-n-tagged: 10
            keep-n-untagged: 10
            older-than: 90 days
            dry-run: true
